spring:
  datasource:
    url: ${datasource.url}
    username: ${datasource.username}
    password: ${datasource.password}
  jpa:
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
commons-mail:
  host: smtp.gmail.com
  port: 587
  username: ${email.username}
  password: ${email.password}
  smtp:
    starttls:
      enable: true
      required: true